/*
  EDIT YOUR CATALOGUE HERE
  ------------------------
  1. Change prices, names or details below and save this file.
  2. Put product photos inside assets/products/.
  3. Set image to the photo path, for example: "assets/products/dairy-milk.jpg".
  4. Copy an existing product block to add another item. Give every product a unique id.
  5. Set active: false to hide a product without deleting it.
*/

window.CATALOG_PRODUCTS = [
  {
    id: 2,
    name: "AdmKiss Coconut Chocolate",
    brand: "Admkiss",
    category: "Chocolates",
    origin: "Imported",
    description:
      "Individually wrapped coconut chocolates in a generous sharing bag.",
    price: 700,
    weight: "300 g",
    type: "Coconut chocolate",
    badge: "Imported",
    color: "#7868b5",
    image: "assets/products/admkiss-coconut-chocolate-transparent.png",
    featured: false,
    active: true,
  },

  {
    id: 4,
    name: "Fruit Marshmallows",
    brand: "Sweet Cloud",
    category: "Candy & jelly",
    origin: "Malaysia",
    description: "Soft, pillowy marshmallows in assorted fruit flavours.",
    price: 385,
    weight: "200 g",
    type: "Soft candy",
    badge: "New",
    color: "#d890b6",
    image: "",
    featured: false,
    active: true,
  },
  {
    id: 5,
    name: "Cashew Nuts (Kaju)",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Vietnam",
    description: "Whole premium cashews, lightly roasted for a clean crunch.",
    price: 450,
    weight: "250 g",
    type: "Roasted nuts",
    badge: "Premium",
    color: "#c68736",
    image: "assets/products/cashew nuts.png",
    featured: true,
    active: true,
  },
  {
    id: 6,
    name: "California Almonds",
    brand: "House Select",
    category: "Dry fruits",
    origin: "United States",
    description: "Crisp whole almonds packed fresh for everyday snacking.",
    price: 450,
    weight: "250 g",
    type: "Raw nuts",
    badge: "",
    color: "#9e653b",
    image: "assets/products/almonds-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 19,
    name: "Roasted Pistachios",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Roasted pistachios in their shells, with a crisp bite and a gently nutty flavour.",
    price: 700,
    weight: "250 g",
    type: "Roasted nuts in shell",
    badge: "",
    color: "#8a9549",
    image: "assets/products/pistachios-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 20,
    name: "Walnut Whole",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Shelled walnut kernels for snacking, breakfast bowls and baking.",
    price: 300,
    weight: "500 g",
    type: "Shelled nuts",
    badge: "",
    color: "#a16b3c",
    image: "assets/products/walnuts-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 21,
    name: "Black Raisins",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Sweet, chewy dried grapes to enjoy on their own or add to cereals and baking.",
    price: 270,
    weight: "250 g",
    type: "Dried grapes",
    badge: "",
    color: "#69413d",
    image: "assets/products/raisins-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 25,
    name: "Golden Raisins",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Sweet golden raisins with a soft, chewy texture for snacking, baking and breakfast bowls.",
    price: 200,
    weight: "250 g",
    type: "Dried grapes",
    badge: "",
    color: "#d59b2d",
    image: "assets/products/golden raisins.jpg",
    featured: false,
    active: true,
  },
  {
    id: 22,
    name: "Dates",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Whole dates with a rich sweetness, ideal for a snack or for chopping into desserts. May contain pits.",
    price: 400,
    weight: "500 g",
    type: "Dried dates",
    badge: "",
    color: "#784b32",
    image: "assets/products/dates-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 23,
    name: "Dried Figs (Anjeer)",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Whole dried figs with a chewy texture and a delicate crunch from their tiny seeds.",
    price: 550,
    weight: "250 g",
    type: "Dried figs",
    badge: "",
    color: "#b88448",
    image: "assets/products/figs-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 24,
    name: "Dried Apricots",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Sweet and tangy dried apricots for snacking, trail mixes and fruit-filled bakes.",
    price: 480,
    weight: "250 g",
    type: "Dried apricots",
    badge: "",
    color: "#df8c2d",
    image: "assets/products/apricots-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 7,
    name: "Danish Butter Cookies",
    brand: "Royal Dansk",
    category: "Biscuits",
    origin: "Denmark",
    description:
      "A classic assortment of crisp, buttery cookies in a keepsake tin.",
    price: 590,
    weight: "340 g",
    type: "Premium biscuits",
    badge: "Giftable",
    color: "#2875aa",
    image: "",
    featured: true,
    active: true,
  },
  {
    id: 8,
    name: "Cranberry Juice",
    brand: "Ocean Spray",
    category: "Juices",
    origin: "United States",
    description: "Refreshing cranberry fruit drink, best served chilled.",
    price: 780,
    weight: "1 L",
    type: "Fruit juice",
    badge: "",
    color: "#a62438",
    image: "",
    featured: false,
    active: true,
  },
  {
    id: 9,
    name: "Shin Ramyun",
    brand: "Nongshim",
    category: "Noodles",
    origin: "South Korea",
    description:
      "Bold, spicy Korean instant noodles with a rich savoury broth.",
    price: 200,
    weight: "120 g",
    type: "Instant ramen",
    badge: "Hot pick",
    color: "#d62f2f",
    image: "",
    featured: true,
    active: true,
  },
  {
    id: 10,
    name: "Wai Wai",
    brand: "Wai Wai",
    category: "Noodles",
    origin: "Nepal",
    description: "Nepal's favourite ready-to-eat chicken-flavoured noodles.",
    price: 550,
    weight: "1 cartoon (30 packs)",
    type: "Instant noodles",
    badge: "Local favourite",
    color: "#e98525",
    image: "",
    featured: false,
    active: true,
  },
  {
    id: 11,
    name: "Tuna in Olive Oil",
    brand: "Marina",
    category: "Pantry",
    origin: "Thailand",
    description: "Tender tuna chunks preserved in smooth olive oil.",
    price: 250,
    weight: "185 g",
    type: "Canned fish",
    badge: "",
    color: "#338b8a",
    image: "",
    featured: false,
    active: true,
  },
  {
    id: 12,
    name: "Spiced Chicken Pickle",
    brand: "Aama's",
    category: "Pantry",
    origin: "Nepal",
    description:
      "Homestyle chicken pickle with warming spices and a bright tang.",
    price: 650,
    weight: "400 g",
    type: "Meat pickle",
    badge: "Small batch",
    color: "#a94b2c",
    image: "",
    featured: true,
    active: true,
  },
  {
    id: 13,
    name: "Samyang Buldak Ramen Assortment",
    brand: "Samyang",
    category: "Noodles",
    origin: "South Korea",
    description:
      "A spicy selection of Buldak hot chicken ramen flavours, including original, 2x spicy, cheese and carbonara.",
    price: 250,
    weight: "Assorted pack sizes",
    type: "Instant ramen",
    badge: "Korean favourite",
    color: "#d83b2f",
    image: "assets/products/buldak-ramen-assortment-transparent.webp",
    featured: true,
    active: true,
  },
  {
    id: 14,
    name: "Imported Chocolate Assortment",
    brand: "Cadbury, Nestlé & more",
    category: "Chocolates",
    origin: "Various",
    description:
      "A rotating assortment of imported milk, dark, nut, wafer and filled chocolate bars.",
    price: null,
    weight: "Various sizes",
    type: "Assorted chocolate bars",
    badge: "Wide selection",
    color: "#60328f",
    image: "assets/products/chocolate-assortment-transparent.webp",
    featured: true,
    active: true,
  },
  {
    id: 15,
    name: "Pringles Assorted Flavours",
    brand: "Pringles",
    category: "Chips & snacks",
    origin: "Imported",
    description:
      "Stackable potato crisps available in a rotating selection of classic and bold flavours.",
    price: 250,
    weight: "Assorted sizes",
    type: "Potato crisps",
    badge: "Multiple flavours",
    color: "#dc2f2f",
    image: "assets/products/pringles-assorted-flavours-transparent.webp",
    featured: true,
    active: true,
  },
  {
    id: 16,
    name: "Raffaello Coconut Chocolates",
    brand: "Ferrero",
    category: "Chocolates",
    origin: "Italy",
    description:
      "Crisp coconut-covered confections with a creamy filling and whole almond centre.",
    price: 1400,
    weight: "15 pieces",
    type: "Coconut almond confection",
    badge: "Premium",
    color: "#d43a2e",
    image: "assets/products/raffaello-coconut-chocolates-transparent.webp",
    featured: true,
    active: true,
  },
  {
    id: 17,
    name: "Runiu Milk Candy",
    brand: "Runniu",
    category: "Candy & jelly",
    origin: "China",
    description:
      "Individually wrapped creamy milk candies with a rich, smooth flavour.",
    price: 550,
    weight: "350 g",
    type: "Milk candy",
    badge: "Imported",
    color: "#1740ad",
    image: "assets/products/runniu-milk-candy-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 3,
    name: "Haribo Goldbears",
    brand: "Haribo",
    category: "Candy & jelly",
    origin: "Germany",
    description: "Bright fruit-flavoured gummy bears with a satisfying chew.",
    price: 480,
    weight: "175 g",
    type: "Gummy candy",
    badge: "",
    color: "#dd4d35",
    image: "",
    featured: true,
    active: true,
  },
  {
    id: 18,
    name: "White Rabbit Creamy Candy",
    brand: "White Rabbit",
    category: "Candy & jelly",
    origin: "China",
    description:
      "Classic chewy milk candy with its signature creamy taste and edible rice-paper wrapping.",
    price: 180,
    weight: "108 g",
    type: "Creamy milk candy",
    badge: "Classic",
    color: "#2155a5",
    image: "assets/products/white-rabbit-creamy-candy-transparent.webp",
    featured: true,
    active: true,
  },
];
