/*
  EDIT YOUR CATALOGUE HERE
  ------------------------
  1. Change prices, names or details below and save this file.
  2. Put product photos inside assets/products/.
  3. Set image to the photo path, for example: "assets/products/dairy-milk.jpg".
  4. Copy an existing product block to add another item. Give every product a unique id.
  5. Set active: false to hide a product without deleting it.
  6. Set inStock: false to replace ordering buttons with an Out of stock label.
*/

window.CATALOG_PRODUCTS = [
  {
    id: 2,
    name: "AdmKiss Coconut Chocolate",
    brand: "Admkiss",
    category: "Chocolates",
    origin: "Imported",
    description:
      "Individually wrapped coconut chocolates in a generous sharing bag.",
    price: 700,
    wholesalePrice: 550,
    weight: "300 g",
    type: "Coconut chocolate",
    badge: "Imported",
    color: "#7868b5",
    image: "assets/products/admkiss-coconut-chocolate-transparent.png",
    featured: false,
    active: true,
  },

  {
    id: 5,
    name: "Cashew Nuts (Kaju)",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Vietnam",
    description: "Whole premium cashews, lightly roasted for a clean crunch.",
    price: 450,
    wholesalePrice: 1700,
    weight: "250 g",
    wholesaleWeight: "1 kg",
    wholesaleMinQuantity: 1,
    type: "Roasted nuts",
    badge: "Premium",
    color: "#c68736",
    image: "assets/products/cashew nuts.png",
    featured: true,
    active: true,
  },
  {
    id: 6,
    name: "California Almonds",
    brand: "House Select",
    category: "Dry fruits",
    origin: "United States",
    description: "Crisp whole almonds packed fresh for everyday snacking.",
    price: 450,
    wholesalePrice: 1700,
    weight: "250 g",
    wholesaleWeight: "1 kg",
    wholesaleMinQuantity: 1,
    type: "Raw nuts",
    badge: "",
    color: "#9e653b",
    image: "assets/products/almonds-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 19,
    name: "Roasted Pistachios",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Roasted pistachios in their shells, with a crisp bite and a gently nutty flavour.",
    price: 700,
    wholesalePrice: 2600,
    weight: "250 g",
    wholesaleWeight: "1 kg",
    wholesaleMinQuantity: 1,
    type: "Roasted nuts in shell",
    badge: "",
    color: "#8a9549",
    image: "assets/products/pistachios-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 20,
    name: "Walnut Whole",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Shelled walnut kernels for snacking, breakfast bowls and baking.",
    price: 300,
    wholesalePrice: 540,
    weight: "500 g",
    wholesaleWeight: "1 kg",
    wholesaleMinQuantity: 1,
    type: "Shelled nuts",
    badge: "",
    color: "#a16b3c",
    image: "assets/products/walnuts-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 21,
    name: "Black Raisins",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Sweet, chewy dried grapes to enjoy on their own or add to cereals and baking.",
    price: 270,
    wholesalePrice: 1000,
    weight: "250 g",
    wholesaleWeight: "1 kg",
    wholesaleMinQuantity: 1,
    type: "Dried grapes",
    badge: "",
    color: "#69413d",
    image: "assets/products/raisins-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 25,
    name: "Golden Raisins",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Sweet golden raisins with a soft, chewy texture for snacking, baking and breakfast bowls.",
    price: 200,
    wholesalePrice: 600,
    weight: "250 g",
    wholesaleWeight: "1 kg",
    wholesaleMinQuantity: 1,
    type: "Dried grapes",
    badge: "",
    color: "#d59b2d",
    image: "assets/products/golden raisins.jpg",
    featured: false,
    active: true,
  },
  {
    id: 22,
    name: "Dates",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Whole dates with a rich sweetness, ideal for a snack or for chopping into desserts. May contain pits.",
    price: 400,
    wholesalePrice: 800,
    weight: "500 g",
    wholesaleWeight: "1 kg",
    wholesaleMinQuantity: 1,
    type: "Dried dates",
    badge: "",
    color: "#784b32",
    image: "assets/products/dates-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 23,
    name: "Dried Figs (Anjeer)",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Whole dried figs with a chewy texture and a delicate crunch from their tiny seeds.",
    price: 550,
    wholesalePrice: 2000,
    weight: "250 g",
    wholesaleWeight: "1 kg",
    wholesaleMinQuantity: 1,
    type: "Dried figs",
    badge: "",
    color: "#b88448",
    image: "assets/products/figs-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 24,
    name: "Dried Apricots",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Sweet and tangy dried apricots for snacking, trail mixes and fruit-filled bakes.",
    price: 480,
    wholesalePrice: 1800,
    weight: "250 g",
    wholesaleWeight: "1 kg",
    wholesaleMinQuantity: 1,
    type: "Dried apricots",
    badge: "",
    color: "#df8c2d",
    image: "assets/products/apricots-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 13,
    name: "Samyang Buldak Ramen Assortment",
    brand: "Samyang",
    category: "Noodles",
    origin: "South Korea",
    description:
      "A spicy selection of Buldak hot chicken ramen flavours, including original, 2x spicy, cheese and carbonara.",
    price: 250,
    wholesalePrice: 200,
    weight: "Assorted pack sizes",
    wholesaleWeight: "Per packet",
    wholesaleMinQuantity: 5,
    type: "Instant ramen",
    badge: "Korean favourite",
    color: "#d83b2f",
    image: "assets/products/buldak-ramen-assortment-transparent.webp",
    featured: true,
    active: true,
  },
  {
    id: 14,
    name: "Imported Chocolate Assortment",
    brand: "Cadbury, Nestlé & more",
    category: "Chocolates",
    origin: "Various",
    description:
      "A rotating assortment of imported milk, dark, nut, wafer and filled chocolate bars.",
    price: null,
    weight: "Various sizes",
    type: "Assorted chocolate bars",
    badge: "Wide selection",
    color: "#60328f",
    image: "assets/products/chocolate-assortment-transparent.webp",
    featured: true,
    active: true,
  },
  {
    id: 15,
    name: "Pringles Assorted Flavours",
    brand: "Pringles",
    category: "Chips & snacks",
    origin: "Imported",
    description:
      "Stackable potato crisps available in a rotating selection of classic and bold flavours.",
    price: 250,
    wholesalePrice: 200,
    weight: "Assorted sizes",
    type: "Potato crisps",
    badge: "Multiple flavours",
    color: "#dc2f2f",
    image: "assets/products/pringles-assorted-flavours-transparent.webp",
    featured: true,
    active: true,
  },
  {
    id: 16,
    name: "Raffaello Coconut Chocolates",
    brand: "Ferrero",
    category: "Chocolates",
    origin: "Italy",
    description:
      "Crisp coconut-covered confections with a creamy filling and whole almond centre.",
    price: 1400,
    wholesalePrice: 1200,
    weight: "15 pieces",
    type: "Coconut almond confection",
    badge: "Premium",
    color: "#d43a2e",
    image: "assets/products/raffaello-coconut-chocolates-transparent.webp",
    featured: true,
    active: true,
  },
  {
    id: 17,
    name: "Runiu Milk Candy",
    brand: "Runniu",
    category: "Candy",
    origin: "China",
    description:
      "Individually wrapped creamy milk candies with a rich, smooth flavour.",
    price: 550,
    wholesalePrice: 450,
    weight: "350 g",
    type: "Milk candy",
    badge: "Imported",
    color: "#1740ad",
    image: "assets/products/runniu-milk-candy-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 18,
    name: "White Rabbit Creamy Candy",
    brand: "White Rabbit",
    category: "Candy",
    origin: "China",
    description:
      "Classic chewy milk candy with its signature creamy taste and edible rice-paper wrapping.",
    price: 180,
    wholesalePrice: 155,
    weight: "108 g",
    type: "Creamy milk candy",
    badge: "Classic",
    color: "#2155a5",
    image: "assets/products/white-rabbit-creamy-candy-transparent.webp",
    featured: true,
    active: true,
  },
  {
    id: 26,
    name: "Yoga Bar Millet Muesli Nuts & Seeds Crunch",
    brand: "Yoga Bar",
    category: "Pantry",
    origin: "",
    description: "Millet muesli with oats, jowar, ragi, nuts and seeds, with no refined sugar stated on the pack.",
    price: 550,
    wholesalePrice: 500,
    weight: "",
    type: "Millet muesli",
    badge: "",
    color: "#e88b20",
    image: "assets/products/yoga-bar-millet-muesli-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 27,
    name: "Jelly Barbecue Sticks",
    brand: "",
    category: "Jelly",
    origin: "Thailand",
    description: "Assorted colourful jelly shapes individually packed on sticks.",
    price: 400,
    wholesalePrice: 360,
    weight: "200 g",
    type: "Jelly candy sticks",
    badge: "",
    color: "#d96d77",
    image: "assets/products/jelly-barbecue-sticks-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 28,
    name: "Queen Snow Jelly",
    brand: "Queen",
    category: "Jelly",
    origin: "Thailand",
    description: "Sugar-coated fruit jelly pieces in assorted colours and wedge shapes.",
    price: 170,
    wholesalePrice: 160,
    weight: "100 g",
    type: "Fruit jelly",
    badge: "",
    color: "#72a7d9",
    image: "assets/products/queen-snow-jelly-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 29,
    name: "Rong Mao Mix Fruit Jelly",
    brand: "Rong Mao",
    category: "Jelly",
    origin: "",
    description: "Individually wrapped mixed fruit jellies in assorted flavours.",
    price: 350,
    wholesalePrice: 300,
    weight: "",
    type: "Fruit jelly",
    badge: "",
    color: "#d99622",
    image: "assets/products/rong-mao-mix-fruit-jelly-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 30,
    name: "TQ Oat Choco Original",
    brand: "TQ",
    category: "Candy",
    origin: "",
    description: "Individually wrapped oat and chocolate snacks in the original flavour.",
    price: 300,
    wholesalePrice: 260,
    weight: "",
    type: "Oat chocolate snack",
    badge: "",
    color: "#3153a3",
    image: "assets/products/tq-oat-choco-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 31,
    name: "Milo Blast Milk Candy",
    brand: "Milo Blast",
    category: "Candy",
    origin: "",
    description: "Individually wrapped milk candies in a resealable sharing bag.",
    price: 250,
    wholesalePrice: 180,
    weight: "80 pieces",
    type: "Milk candy",
    badge: "",
    color: "#259345",
    image: "assets/products/milo-blast-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 32,
    name: "Hello Mallow Blue Twisted Marshmallow",
    brand: "Hello Mallow",
    category: "Candy",
    origin: "",
    description: "Soft pastel marshmallow twists in blue, pink, yellow and white.",
    price: 150,
    wholesalePrice: 120,
    weight: "",
    type: "Twisted marshmallow",
    badge: "",
    color: "#4aa7d9",
    image: "assets/products/hello-mallow-blue-twisted-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 33,
    name: "Fox's Crystal Clear Mints & Fruits",
    brand: "Fox's",
    category: "Candy",
    origin: "",
    description: "An assortment of crystal-clear mint candies and fruit candies in lemon, strawberry, blackcurrant and orange flavours.",
    price: 150,
    wholesalePrice: 120,
    weight: "90 g per bag",
    type: "Hard candy assortment",
    badge: "",
    color: "#3576ba",
    image: "assets/products/foxs-mints-fruits-assortment-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 34,
    name: "Rinda Fruity Jelly",
    brand: "Rinda",
    category: "Jelly",
    origin: "",
    description: "Mixed fruit-flavoured jelly in strawberry, green apple, orange and pineapple flavours.",
    price: 150,
    wholesalePrice: 110,
    weight: "",
    type: "Fruit jelly",
    badge: "",
    color: "#e34f3d",
    image: "assets/products/rinda-fruity-jelly-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 35,
    name: "Gold Fish Jelly Candy",
    brand: "Gold Fish",
    category: "Jelly",
    origin: "Thailand",
    description: "Individually wrapped colourful jelly candies in a sharing bag.",
    price: 120,
    wholesalePrice: 110,
    weight: "",
    type: "Jelly candy",
    badge: "",
    color: "#ef6632",
    image: "assets/products/gold-fish-jelly-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 36,
    name: "Spartan Prawn Crackers",
    brand: "Spartan",
    category: "Chips & snacks",
    origin: "",
    description: "Jumbo pack of small-size prawn crackers for frying and serving as a crisp snack.",
    price: 50,
    wholesalePrice: 40,
    weight: "",
    type: "Uncooked prawn crackers",
    badge: "",
    color: "#26a6d1",
    image: "assets/products/spartan-prawn-crackers-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 37,
    name: "Runniu Milk Candy",
    brand: "Runniu",
    category: "Candy",
    origin: "China",
    description: "Individually wrapped milk candies in a large sharing bag.",
    price: 280,
    wholesalePrice: 255,
    weight: "160 g",
    type: "Milk candy",
    badge: "",
    color: "#426cbb",
    image: "assets/products/runniu-milk-candy-160g-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 38,
    name: "Prairie My Chewy Candy Mix Flavor",
    brand: "Prairie",
    category: "Candy",
    origin: "",
    description: "Individually wrapped chewy candies in assorted fruit and sweetcorn flavours.",
    price: 250,
    wholesalePrice: 200,
    weight: "100 pieces",
    type: "Chewy candy",
    badge: "",
    color: "#78a463",
    image: "assets/products/prairie-my-chewy-candy-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 39,
    name: "Nuts Crisp Assorted Candy",
    brand: "Nuts Crisp",
    category: "Candy",
    origin: "",
    description: "Individually wrapped assorted nut candies in a resealable sharing bag.",
    price: 300,
    wholesalePrice: 250,
    weight: "250 g",
    type: "Nut candy assortment",
    badge: "",
    color: "#b47a32",
    image: "assets/products/nuts-crisp-250g-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 40,
    name: "Amin Dates Kalmi Dates",
    brand: "Amin Dates",
    category: "Dry fruits",
    origin: "",
    description: "Kalmi dates packed in a reusable clear jar.",
    price: 550,
    wholesalePrice: 500,
    weight: "400 g",
    wholesaleWeight: "400 g bottle",
    type: "Whole dates",
    badge: "",
    color: "#8e2830",
    image: "assets/products/amin-kalmi-dates-400g-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 41,
    name: "Vacuum-Packed Whole Dates",
    brand: "",
    category: "Dry fruits",
    origin: "",
    description: "Whole dates sealed in a compact vacuum pack.",
    price: 300,
    wholesalePrice: 250,
    weight: "",
    wholesaleWeight: "1 pack",
    type: "Whole dates",
    badge: "",
    color: "#7f432d",
    image: "assets/products/vacuum-packed-dates-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 42,
    name: "Kugu Chocolatier Special Assortment",
    brand: "Kugu",
    category: "Chocolates",
    origin: "Algeria",
    description: "Assorted individually wrapped cream-filled flavoured compound chocolates.",
    price: 500,
    wholesalePrice: 430,
    weight: "",
    type: "Chocolate assortment",
    badge: "",
    color: "#24799c",
    image: "assets/products/kugu-chocolatier-special-assortment-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 43,
    name: "MacCoffee Mini Original 3-in-1",
    brand: "MacCoffee",
    category: "Beverages",
    origin: "",
    description: "Original 3-in-1 instant coffee mix in individual mini sachets.",
    price: 350,
    wholesalePrice: 320,
    weight: "192 g · 15 sachets",
    type: "Instant coffee mix",
    badge: "",
    color: "#c9882e",
    image: "assets/products/maccoffee-mini-original-3in1-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 44,
    name: "Soray Wocci Coconut",
    brand: "Soray",
    category: "Chocolates",
    origin: "",
    description: "Individually wrapped coconut bars covered in compound chocolate.",
    price: 750,
    wholesalePrice: 650,
    weight: "",
    type: "Chocolate coconut bar",
    badge: "",
    color: "#79503b",
    image: "assets/products/soray-wocci-coconut-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 45,
    name: "Melosa Mongolian Salt Tea",
    brand: "Melosa",
    category: "Beverages",
    origin: "",
    description: "Instant 3-in-1 Mongolian salt tea mix in individual sachets.",
    price: 400,
    wholesalePrice: 380,
    weight: "240 g · 20 sachets",
    type: "Instant salt tea",
    badge: "",
    color: "#5c9f36",
    image: "assets/products/melosa-mongolian-salt-tea-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 46,
    name: "Derby Premium Candy Assortment",
    brand: "Derby Premium",
    category: "Candy",
    origin: "India",
    description: "Assorted Dubai Kunafa Coffees, coconut-filled chocolate shells and Embossie birthday candies.",
    price: 100,
    wholesalePrice: 90,
    weight: "",
    type: "Assorted filled candy",
    badge: "",
    color: "#8d5433",
    image: "assets/products/derby-premium-candy-assortment-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 47,
    name: "Sour Bandz Rainbow Punch",
    brand: "Fun Factory",
    category: "Candy",
    origin: "",
    description: "Rainbow Punch super-sour candy strips in a resealable bag.",
    price: 150,
    wholesalePrice: 120,
    weight: "120 g · 12 strips",
    type: "Sour candy strips",
    badge: "",
    color: "#7a4db1",
    image: "assets/products/sour-bandz-rainbow-punch-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 48,
    name: "Agri Foods Macaron by Noura",
    brand: "Agri Foods",
    category: "Biscuits",
    origin: "",
    description: "Colourful macaron-style center-filled biscuits in a resealable sharing pouch.",
    price: 250,
    wholesalePrice: 200,
    weight: "",
    type: "Center-filled biscuits",
    badge: "",
    color: "#d66d98",
    image: "assets/products/agri-foods-macaron-by-noura-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 49,
    name: "Shanti's Instant Oats",
    brand: "Shanti's",
    category: "Pantry",
    origin: "",
    description: "Whole-grain instant oats in a reusable jar, ready in about three minutes.",
    price: 230,
    wholesalePrice: 200,
    weight: "400 g",
    type: "Instant oats",
    badge: "",
    color: "#d6a633",
    image: "assets/products/shantis-instant-oats-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 50,
    name: "Bonfire Fruit Tella Mango Gummy",
    brand: "Bonfire",
    category: "Jelly",
    origin: "",
    description: "Sweet-and-sour mango-shaped vegan gummies.",
    price: 150,
    wholesalePrice: 120,
    weight: "120 g",
    type: "Mango gummy candy",
    badge: "",
    color: "#e29a23",
    image: "assets/products/bonfire-fruit-tella-mango-gummy-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 51,
    name: "Alpenliebe Creamfills Butter Toffee",
    brand: "Alpenliebe",
    category: "Candy",
    origin: "",
    description: "Butter toffee candies with a creamy centre filling.",
    price: 350,
    wholesalePrice: 300,
    weight: "",
    type: "Center-filled toffee",
    badge: "",
    color: "#d78927",
    image: "assets/products/alpenliebe-creamfills-butter-toffee-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 52,
    name: "Derby Happy Birthday Candy",
    brand: "Derby",
    category: "Candy",
    origin: "India",
    description: "Fruit-flavoured center-filled candies in raw mango, strawberry, mango and orange flavours.",
    price: 100,
    wholesalePrice: 90,
    weight: "",
    type: "Center-filled fruit candy",
    badge: "",
    color: "#dc733d",
    image: "assets/products/derby-happy-birthday-candy-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 53,
    name: "Derby Darling Velvetto",
    brand: "Derby",
    category: "Candy",
    origin: "India",
    description: "Fruit-flavoured heart-shaped candies in an assortment of eight flavours.",
    price: 100,
    wholesalePrice: 90,
    weight: "",
    type: "Fruit candy assortment",
    badge: "",
    color: "#c64676",
    image: "assets/products/derby-darling-velvetto-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 54,
    name: "Nongshim Shin Ramyun 5-Pack",
    brand: "Nongshim",
    category: "Noodles",
    origin: "South Korea",
    description: "Spicy instant noodle multipack with five 120 g packs and a promotional photocard inside.",
    price: 900,
    wholesalePrice: 850,
    weight: "600 g · 5 packs",
    type: "Instant ramen multipack",
    badge: "",
    color: "#c82227",
    image: "assets/products/nongshim-shin-ramyun-5-pack-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 55,
    name: "A-Taste Soda Biscuit Butter Parsley",
    brand: "A-Taste",
    category: "Biscuits",
    origin: "",
    description: "Crisp butter-and-parsley soda biscuits with no sugar added stated on the pack.",
    price: 400,
    wholesalePrice: 350,
    weight: "270 g",
    type: "Soda biscuits",
    badge: "",
    color: "#73954b",
    image: "assets/products/a-taste-soda-biscuit-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 56,
    name: "Bisk Club Vegetable Crackers",
    brand: "Bisk Club",
    category: "Biscuits",
    origin: "",
    description: "Crunchy vegetable-flavoured crackers in a sharing pack.",
    price: 250,
    wholesalePrice: 220,
    weight: "240 g",
    type: "Vegetable crackers",
    badge: "",
    color: "#67a447",
    image: "assets/products/bisk-club-vegetable-crackers-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 57,
    name: "Malkist Cheese Crackers",
    brand: "Malkist",
    category: "Biscuits",
    origin: "",
    description: "Cheese-flavoured crunchy layered sandwich crackers with a sugar sprinkle.",
    price: 80,
    wholesalePrice: 70,
    weight: "8 sandwich crackers",
    type: "Layered cracker biscuits",
    badge: "",
    color: "#e4a42f",
    image: "assets/products/malkist-cheese-crackers-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 58,
    name: "Lotte Choco Pie Original",
    brand: "Lotte",
    category: "Biscuits",
    origin: "India",
    description: "Soft cake pies with a rich marshmallow centre and chocolate coating.",
    price: 150,
    wholesalePrice: 120,
    weight: "6 pieces",
    type: "Chocolate marshmallow pie",
    badge: "",
    color: "#8e2831",
    image: "assets/products/lotte-choco-pie-original-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 59,
    name: "A-Taste Lemon Thin Biscuit",
    brand: "A-Taste",
    category: "Biscuits",
    origin: "",
    description: "Thin crisp lemon-flavoured biscuits in individually wrapped portions.",
    price: 350,
    wholesalePrice: 320,
    weight: "230 g",
    type: "Lemon thin biscuits",
    badge: "",
    color: "#dcad35",
    image: "assets/products/a-taste-lemon-thin-biscuit-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 60,
    name: "Sunfeast Dark Fantasy Choco Fills",
    brand: "Sunfeast",
    category: "Biscuits",
    origin: "Nepal",
    description: "Original cookies with a flowing chocolate centre filling.",
    price: 90,
    wholesalePrice: 75,
    weight: "",
    type: "Chocolate-filled cookies",
    badge: "",
    color: "#5b342c",
    image: "assets/products/dark-fantasy-choco-fills-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 61,
    name: "Bikano Soan Papdi",
    brand: "Bikano",
    category: "Candy",
    origin: "",
    description: "Soft, sweet soan papdi garnished with dry fruits.",
    price: 200,
    wholesalePrice: 190,
    weight: "250 g",
    type: "Indian sweet",
    badge: "",
    color: "#b6492e",
    image: "assets/products/bikano-soan-papdi-transparent.webp",
    featured: false,
    active: true,
  },
];
