/*
  EDIT YOUR CATALOGUE HERE
  ------------------------
  1. Change prices, names or details below and save this file.
  2. Put product photos inside assets/products/.
  3. Set image to the photo path, for example: "assets/products/dairy-milk.jpg".
  4. Copy an existing product block to add another item. Give every product a unique id.
  5. Set active: false to hide a product without deleting it.
*/

window.CATALOG_PRODUCTS = [
  {
    id: 2,
    name: "AdmKiss Coconut Chocolate",
    brand: "Admkiss",
    category: "Chocolates",
    origin: "Imported",
    description:
      "Individually wrapped coconut chocolates in a generous sharing bag.",
    price: 700,
    weight: "300 g",
    type: "Coconut chocolate",
    badge: "Imported",
    color: "#7868b5",
    image: "assets/products/admkiss-coconut-chocolate-transparent.png",
    featured: false,
    active: true,
  },

  {
    id: 5,
    name: "Cashew Nuts (Kaju)",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Vietnam",
    description: "Whole premium cashews, lightly roasted for a clean crunch.",
    price: 450,
    weight: "250 g",
    type: "Roasted nuts",
    badge: "Premium",
    color: "#c68736",
    image: "assets/products/cashew nuts.png",
    featured: true,
    active: true,
  },
  {
    id: 6,
    name: "California Almonds",
    brand: "House Select",
    category: "Dry fruits",
    origin: "United States",
    description: "Crisp whole almonds packed fresh for everyday snacking.",
    price: 450,
    weight: "250 g",
    type: "Raw nuts",
    badge: "",
    color: "#9e653b",
    image: "assets/products/almonds-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 19,
    name: "Roasted Pistachios",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Roasted pistachios in their shells, with a crisp bite and a gently nutty flavour.",
    price: 700,
    weight: "250 g",
    type: "Roasted nuts in shell",
    badge: "",
    color: "#8a9549",
    image: "assets/products/pistachios-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 20,
    name: "Walnut Whole",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Shelled walnut kernels for snacking, breakfast bowls and baking.",
    price: 300,
    weight: "500 g",
    type: "Shelled nuts",
    badge: "",
    color: "#a16b3c",
    image: "assets/products/walnuts-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 21,
    name: "Black Raisins",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Sweet, chewy dried grapes to enjoy on their own or add to cereals and baking.",
    price: 270,
    weight: "250 g",
    type: "Dried grapes",
    badge: "",
    color: "#69413d",
    image: "assets/products/raisins-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 25,
    name: "Golden Raisins",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Sweet golden raisins with a soft, chewy texture for snacking, baking and breakfast bowls.",
    price: 200,
    weight: "250 g",
    type: "Dried grapes",
    badge: "",
    color: "#d59b2d",
    image: "assets/products/golden raisins.jpg",
    featured: false,
    active: true,
  },
  {
    id: 22,
    name: "Dates",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Whole dates with a rich sweetness, ideal for a snack or for chopping into desserts. May contain pits.",
    price: 400,
    weight: "500 g",
    type: "Dried dates",
    badge: "",
    color: "#784b32",
    image: "assets/products/dates-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 23,
    name: "Dried Figs (Anjeer)",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Whole dried figs with a chewy texture and a delicate crunch from their tiny seeds.",
    price: 550,
    weight: "250 g",
    type: "Dried figs",
    badge: "",
    color: "#b88448",
    image: "assets/products/figs-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 24,
    name: "Dried Apricots",
    brand: "House Select",
    category: "Dry fruits",
    origin: "Imported",
    description: "Sweet and tangy dried apricots for snacking, trail mixes and fruit-filled bakes.",
    price: 480,
    weight: "250 g",
    type: "Dried apricots",
    badge: "",
    color: "#df8c2d",
    image: "assets/products/apricots-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 13,
    name: "Samyang Buldak Ramen Assortment",
    brand: "Samyang",
    category: "Noodles",
    origin: "South Korea",
    description:
      "A spicy selection of Buldak hot chicken ramen flavours, including original, 2x spicy, cheese and carbonara.",
    price: 250,
    weight: "Assorted pack sizes",
    type: "Instant ramen",
    badge: "Korean favourite",
    color: "#d83b2f",
    image: "assets/products/buldak-ramen-assortment-transparent.webp",
    featured: true,
    active: true,
  },
  {
    id: 14,
    name: "Imported Chocolate Assortment",
    brand: "Cadbury, Nestlé & more",
    category: "Chocolates",
    origin: "Various",
    description:
      "A rotating assortment of imported milk, dark, nut, wafer and filled chocolate bars.",
    price: null,
    weight: "Various sizes",
    type: "Assorted chocolate bars",
    badge: "Wide selection",
    color: "#60328f",
    image: "assets/products/chocolate-assortment-transparent.webp",
    featured: true,
    active: true,
  },
  {
    id: 15,
    name: "Pringles Assorted Flavours",
    brand: "Pringles",
    category: "Chips & snacks",
    origin: "Imported",
    description:
      "Stackable potato crisps available in a rotating selection of classic and bold flavours.",
    price: 250,
    weight: "Assorted sizes",
    type: "Potato crisps",
    badge: "Multiple flavours",
    color: "#dc2f2f",
    image: "assets/products/pringles-assorted-flavours-transparent.webp",
    featured: true,
    active: true,
  },
  {
    id: 16,
    name: "Raffaello Coconut Chocolates",
    brand: "Ferrero",
    category: "Chocolates",
    origin: "Italy",
    description:
      "Crisp coconut-covered confections with a creamy filling and whole almond centre.",
    price: 1400,
    weight: "15 pieces",
    type: "Coconut almond confection",
    badge: "Premium",
    color: "#d43a2e",
    image: "assets/products/raffaello-coconut-chocolates-transparent.webp",
    featured: true,
    active: true,
  },
  {
    id: 17,
    name: "Runiu Milk Candy",
    brand: "Runniu",
    category: "Candy & jelly",
    origin: "China",
    description:
      "Individually wrapped creamy milk candies with a rich, smooth flavour.",
    price: 550,
    weight: "350 g",
    type: "Milk candy",
    badge: "Imported",
    color: "#1740ad",
    image: "assets/products/runniu-milk-candy-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 18,
    name: "White Rabbit Creamy Candy",
    brand: "White Rabbit",
    category: "Candy & jelly",
    origin: "China",
    description:
      "Classic chewy milk candy with its signature creamy taste and edible rice-paper wrapping.",
    price: 180,
    weight: "108 g",
    type: "Creamy milk candy",
    badge: "Classic",
    color: "#2155a5",
    image: "assets/products/white-rabbit-creamy-candy-transparent.webp",
    featured: true,
    active: true,
  },
  {
    id: 26,
    name: "Yoga Bar Millet Muesli Nuts & Seeds Crunch",
    brand: "Yoga Bar",
    category: "Pantry",
    origin: "",
    description: "Millet muesli with oats, jowar, ragi, nuts and seeds, with no refined sugar stated on the pack.",
    price: null,
    weight: "",
    type: "Millet muesli",
    badge: "",
    color: "#e88b20",
    image: "assets/products/yoga-bar-millet-muesli-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 27,
    name: "Jelly Barbecue Sticks",
    brand: "",
    category: "Candy & jelly",
    origin: "Thailand",
    description: "Assorted colourful jelly shapes individually packed on sticks.",
    price: 400,
    weight: "200 g",
    type: "Jelly candy sticks",
    badge: "",
    color: "#d96d77",
    image: "assets/products/jelly-barbecue-sticks-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 28,
    name: "Queen Snow Jelly",
    brand: "Queen",
    category: "Candy & jelly",
    origin: "Thailand",
    description: "Sugar-coated fruit jelly pieces in assorted colours and wedge shapes.",
    price: 170,
    weight: "100 g",
    type: "Fruit jelly",
    badge: "",
    color: "#72a7d9",
    image: "assets/products/queen-snow-jelly-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 29,
    name: "Rong Mao Mix Fruit Jelly",
    brand: "Rong Mao",
    category: "Candy & jelly",
    origin: "",
    description: "Individually wrapped mixed fruit jellies in assorted flavours.",
    price: 350,
    weight: "",
    type: "Fruit jelly",
    badge: "",
    color: "#d99622",
    image: "assets/products/rong-mao-mix-fruit-jelly-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 30,
    name: "TQ Oat Choco Original",
    brand: "TQ",
    category: "Candy & jelly",
    origin: "",
    description: "Individually wrapped oat and chocolate snacks in the original flavour.",
    price: 300,
    weight: "",
    type: "Oat chocolate snack",
    badge: "",
    color: "#3153a3",
    image: "assets/products/tq-oat-choco-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 31,
    name: "Milo Blast Milk Candy",
    brand: "Milo Blast",
    category: "Candy & jelly",
    origin: "",
    description: "Individually wrapped milk candies in a resealable sharing bag.",
    price: 250,
    weight: "80 pieces",
    type: "Milk candy",
    badge: "",
    color: "#259345",
    image: "assets/products/milo-blast-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 32,
    name: "Hello Mallow Blue Twisted Marshmallow",
    brand: "Hello Mallow",
    category: "Candy & jelly",
    origin: "",
    description: "Soft pastel marshmallow twists in blue, pink, yellow and white.",
    price: 150,
    weight: "",
    type: "Twisted marshmallow",
    badge: "",
    color: "#4aa7d9",
    image: "assets/products/hello-mallow-blue-twisted-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 33,
    name: "Fox's Crystal Clear Mints & Fruits",
    brand: "Fox's",
    category: "Candy & jelly",
    origin: "",
    description: "An assortment of crystal-clear mint candies and fruit candies in lemon, strawberry, blackcurrant and orange flavours.",
    price: 150,
    weight: "90 g per bag",
    type: "Hard candy assortment",
    badge: "",
    color: "#3576ba",
    image: "assets/products/foxs-mints-fruits-assortment-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 34,
    name: "Rinda Fruity Jelly",
    brand: "Rinda",
    category: "Candy & jelly",
    origin: "",
    description: "Mixed fruit-flavoured jelly in strawberry, green apple, orange and pineapple flavours.",
    price: 150,
    weight: "",
    type: "Fruit jelly",
    badge: "",
    color: "#e34f3d",
    image: "assets/products/rinda-fruity-jelly-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 35,
    name: "Gold Fish Jelly Candy",
    brand: "Gold Fish",
    category: "Candy & jelly",
    origin: "Thailand",
    description: "Individually wrapped colourful jelly candies in a sharing bag.",
    price: 120,
    weight: "",
    type: "Jelly candy",
    badge: "",
    color: "#ef6632",
    image: "assets/products/gold-fish-jelly-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 36,
    name: "Spartan Prawn Crackers",
    brand: "Spartan",
    category: "Chips & snacks",
    origin: "",
    description: "Jumbo pack of small-size prawn crackers for frying and serving as a crisp snack.",
    price: 50,
    weight: "",
    type: "Uncooked prawn crackers",
    badge: "",
    color: "#26a6d1",
    image: "assets/products/spartan-prawn-crackers-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 37,
    name: "Runniu Milk Candy",
    brand: "Runniu",
    category: "Candy & jelly",
    origin: "China",
    description: "Individually wrapped milk candies in a large sharing bag.",
    price: 280,
    weight: "160 g",
    type: "Milk candy",
    badge: "",
    color: "#426cbb",
    image: "assets/products/runniu-milk-candy-160g-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 38,
    name: "Prairie My Chewy Candy Mix Flavor",
    brand: "Prairie",
    category: "Candy & jelly",
    origin: "",
    description: "Individually wrapped chewy candies in assorted fruit and sweetcorn flavours.",
    price: 250,
    weight: "100 pieces",
    type: "Chewy candy",
    badge: "",
    color: "#78a463",
    image: "assets/products/prairie-my-chewy-candy-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 39,
    name: "Nuts Crisp Assorted Candy",
    brand: "Nuts Crisp",
    category: "Candy & jelly",
    origin: "",
    description: "Individually wrapped assorted nut candies in a resealable sharing bag.",
    price: 300,
    weight: "250 g",
    type: "Nut candy assortment",
    badge: "",
    color: "#b47a32",
    image: "assets/products/nuts-crisp-250g-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 40,
    name: "Amin Dates Kalmi Dates",
    brand: "Amin Dates",
    category: "Dry fruits",
    origin: "",
    description: "Kalmi dates packed in a reusable clear jar.",
    price: 550,
    weight: "400 g",
    type: "Whole dates",
    badge: "",
    color: "#8e2830",
    image: "assets/products/amin-kalmi-dates-400g-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 41,
    name: "Vacuum-Packed Whole Dates",
    brand: "",
    category: "Dry fruits",
    origin: "",
    description: "Whole dates sealed in a compact vacuum pack.",
    price: 300,
    weight: "",
    type: "Whole dates",
    badge: "",
    color: "#7f432d",
    image: "assets/products/vacuum-packed-dates-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 42,
    name: "Kugu Chocolatier Special Assortment",
    brand: "Kugu",
    category: "Chocolates",
    origin: "Algeria",
    description: "Assorted individually wrapped cream-filled flavoured compound chocolates.",
    price: 500,
    weight: "",
    type: "Chocolate assortment",
    badge: "",
    color: "#24799c",
    image: "assets/products/kugu-chocolatier-special-assortment-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 43,
    name: "MacCoffee Mini Original 3-in-1",
    brand: "MacCoffee",
    category: "Pantry",
    origin: "",
    description: "Original 3-in-1 instant coffee mix in individual mini sachets.",
    price: 350,
    weight: "192 g · 15 sachets",
    type: "Instant coffee mix",
    badge: "",
    color: "#c9882e",
    image: "assets/products/maccoffee-mini-original-3in1-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 44,
    name: "Soray Wocci Coconut",
    brand: "Soray",
    category: "Chocolates",
    origin: "",
    description: "Individually wrapped coconut bars covered in compound chocolate.",
    price: 750,
    weight: "",
    type: "Chocolate coconut bar",
    badge: "",
    color: "#79503b",
    image: "assets/products/soray-wocci-coconut-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 45,
    name: "Melosa Mongolian Salt Tea",
    brand: "Melosa",
    category: "Pantry",
    origin: "",
    description: "Instant 3-in-1 Mongolian salt tea mix in individual sachets.",
    price: 400,
    weight: "240 g · 20 sachets",
    type: "Instant salt tea",
    badge: "",
    color: "#5c9f36",
    image: "assets/products/melosa-mongolian-salt-tea-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 46,
    name: "Derby Premium Candy Assortment",
    brand: "Derby Premium",
    category: "Candy & jelly",
    origin: "India",
    description: "Assorted Dubai Kunafa Coffees, coconut-filled chocolate shells and Embossie birthday candies.",
    price: 120,
    weight: "",
    type: "Assorted filled candy",
    badge: "",
    color: "#8d5433",
    image: "assets/products/derby-premium-candy-assortment-transparent.webp",
    featured: false,
    active: true,
  },
  {
    id: 47,
    name: "Sour Bandz Rainbow Punch",
    brand: "Fun Factory",
    category: "Candy & jelly",
    origin: "",
    description: "Rainbow Punch super-sour candy strips in a resealable bag.",
    price: 150,
    weight: "120 g · 12 strips",
    type: "Sour candy strips",
    badge: "",
    color: "#7a4db1",
    image: "assets/products/sour-bandz-rainbow-punch-transparent.webp",
    featured: false,
    active: true,
  },
];
